### PR TITLE
Finish refactor to useReducer and bug fix

### LINKED ISSUE #207: Inline Renaming: make 'Escape' cancel
As a user of VZCode who thought about renaming a file but then decided against it, I want to have the 'Escape' key signal to VZCode to _cancel_ the changes (do not commit the rename)

See `src/client/Sidebar/Item.tsx` line 22

### LINKED ISSUE #237: Refactor State to Reducer
As a developer of VZCode, I want the codebase to be clean and well organized, so that I can easily add new features.

Currently there are many instances of `useState`, and there are operations that need to touch many different state pieces at once. This approach is cumbersome and error-prone. We can refactor these to use `useReducer` to achieve a cleaner codebase with clean separation of concerns across code files.

Pieces of state to migrate into this paradigm (in no particular order):

 * [x] `tabList` #235 
 * [ ] `activeFileId`
 * [ ] `theme`
 * [ ] `isSettingsOpen`
 * [ ] Presence stuff maybe? `localPresence` and `docPresence` Might not make sense... not sure

### PR DESCRIPTION
**Pull request by EvWhymark**
Closes #237 
Closes #207 

Finishes the refactor to useReducer. Focused on keeping the reducer functions pure and added useCallback to the dispatch functions. As the codebase continues to expand people can continue to add states to our reducer however we have currently moved most major useStates over to the useReducer react hook. Also went ahead and deleted useTabsState.ts. Currently is obsolete and all functionality has been migrated over to reducer.ts.

Also noticed a really quick fix with issue #207. Just a quick one line fix in the sidebar that turns off renaming if escape is pressed.

### CODE REVIEW

File: src/client/App.tsx [hunk 1]
```diff
@@ -153,87 +153,99 @@ function App() {
...
-      activeFileId,
-    });
-  };
-  const openTab = (fileId: FileId) => {
-    dispatch({
-      type: 'open_tab',
-      fileId,
-    });
-  };
+  const setTabList = useCallback(
```
Comment (curran) [inline src/client/App.tsx:172]: Nice!

File: src/client/App.tsx [hunk 2]
```diff
@@ -153,87 +153,99 @@ function App() {
...
+      dispatch({
+        type: 'set_Theme',
+        themeLabel: themeLabel,
+      });
+    },
+    [dispatch],
+  );
+
+  // True to show the settings modal.
+  const setIsSettingsOpen = useCallback(
```
Comment (curran) [inline src/client/App.tsx:233]: Excellent collection of functions that dispatch actions!

I could imagine moving all of these into a separate module.

Similar pattern is here from the old days of Redux: https://react-redux.js.org/using-react-redux/connect-mapdispatch

File: src/client/Sidebar/Item.tsx [hunk 3]
```diff
@@ -19,9 +19,9 @@ export const Item = ({
   const [renameValue, setRenameValue] = useState('');
 
   const onKeyDown = useCallback((event) => {
-    // TODO make 'Escape' cancel the changes - do not commit the rename
-    // https://github.com/vizhub-core/vzcode/issues/207
-    if (event.key === 'Enter' || event.key === 'Escape') {
+    if (event.key === 'Escape') {
```
Comment (curran) [inline src/client/Sidebar/Item.tsx:22]: Very nice!

File: src/client/reducer.ts [hunk 4]
```diff
@@ -1,11 +1,16 @@
 import { FileId } from '../types';
+import { act } from 'react-dom/test-utils';
 
 export const reducer = (state, action) => {
   switch (action.type) {
     // TODO phase this out
+
+    // The ordered list of tabs.
+    // TODO make this a URL param
     case 'set_tab_list': {
```
Comment (curran) [inline src/client/reducer.ts:10]: The next level of the refactoring would be to remove this.

**Review by curran — APPROVED** [review]
Excellent work! Thank you so much.

**Comment by curran** [comment]
You may appreciate this commit https://github.com/vizhub-core/vzcode/commit/b90cdc29bb1c2576dfa37f00893f17c3dafea0f4

I meant to make it a PR but accidentally pushed to main 🤦
